version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:10
      - image: trufflesuite/ganache-cli:v6.1.8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies
      - run: npm install truffle@5.0.7
      - run: npm run test
workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - test:
          requires:
            - build
