version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:10.0
      - image: gtaschuk/testrpc
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies
      - run: sudo npm install -g truffle
      - run: truffle test --network test
workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - test:
          requires:
            - build
